### ISSUE TITLE
Detekcija bolesti lista paradajza

### ISSUE THREAD

**Issue by miloszeljko00** [ftn-ai-lab/nm-2023#1]
## **Repository:**
https://github.com/miloszeljko00/AgroScan
## **Tim:**
Miloš Zeljko E2 12/2023

## **Definicija problema:**
Ideja projekta je izrada sistema za prepoznavanje i detekciju bolesti lista paradajza. Sistem bi trebao da klasifikuje slike listova paradajza na zdrave i bolesne. Pored toga, ukoliko je bolest prisutna, treba odrediti koja. Sistem bi trebao da podrži klasifikaciju na 10 klasa, 9 bolesti (bakterijske tačke, rana plamenjača, kasna plamenjača, plesnivost lista paradajza, siva pegavost lista, dvopegasta paukova grinja, virus mozaika paradajza, crna pegavost, virus uvijanja žutog lista) i zdrave.

## **Skup podataka:**
„Plant Village dataset“ (https://www.kaggle.com/datasets/emmarex/plantdisease) – Skup podataka od 54.303 „RGB“ slika 14 različitih vrsta biljaka grupisanih u 38 klasa. Za paradajz poseduje oko 15.000 slika, raspoređenih na 10 klasa. Slike su dimenzija 256x256 jpeg formata.

## **Metodologija:**
Za početak, plan je izvršiti augmentaciju slika, kako bi se izbalansirao broj slika između klasa i postigla bolja tačnost modela. Neke od augmentacija koje će biti oprobane su: rotacija, zumiranje, promena osvetljenja, vertikalno i horizontalno preslikavanje. S obzirom da su slike iz skupa podataka prikupljene u laboratorijskim uslovima, poprilično su kvalitetne pa neko dodatno pretprocesiranje neće biti neophodno. Međutim, biće eksperimentisano sa različitim filterima, poput zamućivanja i izoštravanja slika i veštačkog podizanja i spuštanja rezolucija slika. Zatim će se ekperimentisati sa arhitekturom konvolutivne neuronske mreže. Vršiće se dotreniravanje i "fine tuning" sledećih poznatih arhitektura konvolutivnih neuronskih mreža: „VGG“, „ResNet“, „InceptionV3“ i „Xception“. Cilj će biti da se izvrši što bolja klasifikacija na jednu od 10 klasa. Nakon svega biće odrađena analiza i interpretacija kako model donosi odluku o klasi kojoj slika pripada.

## **Evaluacija:**
Kao metod evaluacije koristiće se tačnost, koja se definiše sledećom formulom:
![image](https://github.com/ftn-ai-lab/nm-2023/assets/37379314/0c68da67-0258-4027-97be-7781c2226063)
Pored tačnosti posmatraćemo i „Fmacro“ meru koju ćemo računati kao prosečnu vrednost „F1“ mera svake od klasa po sledećoj formuli:
![image](https://github.com/ftn-ai-lab/nm-2023/assets/37379314/0002fc0a-a0d5-4f33-a16c-b22b8e4354f6)
„F1“ predstavlja balansiranu meru između preciznosti i odziva i definisana je sledećom formulom:
![image](https://github.com/ftn-ai-lab/nm-2023/assets/37379314/5dd16b2a-abd5-4987-916c-133245c5b292)
Preciznost predstavlja meru tačnosti pozitivnih pogađanja i računa se formulom:
![image](https://github.com/ftn-ai-lab/nm-2023/assets/37379314/93efc04e-bcec-4e44-bd8e-7d70bd3d84e2)
Одзив представља меру модела да ухвати све позитивне примере и рачуна се формулом:
![image](https://github.com/ftn-ai-lab/nm-2023/assets/37379314/02095c74-8a29-45d3-a980-a08a2e8a26ee)
Inicijalni skup podataka pre augmentacije slika, koja će se vršiti samo nad trening skupom, će biti podeljen u sledećem odnosu: trening skup 50%, validacioni skup 30% i testni skup 20%. Podela u procentima će se vršiti na nivou klasa, a ne ukupnog broja slika, kako bi se sačuvao inicijalni odnos broja slika po klasama. Kao funkcija greške biće korišćena kategorička unakrsna entropija. Na kraju rada biće odrađena analiza grešaka modela i opisani primeri na kojim je model pravio najviše grešaka pri klasifikaciji.

**Comment by vdragan1993** [comment]
Izvršite korekciju podele tako da testni skup ima barem 20%.

Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
