### ISSUE TITLE
Detekcija sklonosti glasanja moderne Evrovizije

### ISSUE THREAD

**Issue by MilanPodunavac** [ftn-ai-lab/nm-2023#10]
**Tim**

Milan Podunavac, E2-44/2022
https://github.com/MilanPodunavac/EurovisionVotingAnalyzer

**Definicija problema**

Evrovizija je najpopularnije muzičko takmičenje na starom kontinentu, i jedan od najuticajnijih kulturnih događaja tokom godine. Učestvovanje umetnika na takmičenju se odlučuje na nivou nacije, najveći televizijski organi organizuju velike festivale ili interne audicije da nađu nastup koji će predstavljati državu pred svetskom publikom. Dobar rezultat na takmičenju donosi prestiž i popularnost ne samo umetniku već i čitavoj državi, pa su rezultati takmičenja često meta skeptika koji se pitaju da li je glasanje motivisano samo kvalitetom nastupa ili su uključeni razni politički razlozi u izbor pobednika. Druge studija glasanja su došle do zaključka da ne postoji primetno odstupanje konačnih rezultata od onih koji bi mogli biti objašnjeni samim kvalitetom nastupa, međutim, veliki deo kritika i skandala vezanih za glasanje su osetni na nivou država. Cilj ovog projekta jeste identifikacija koliko na individualno glasanje država utiču kvalitet nastupa, lični ukusi glasača i internacionalna politička scena.

**Skup podataka**

[Glavni skup podataka](https://www.kaggle.com/datasets/diamondsnake/eurovision-song-contest-data) sadrži glavne podatke o svim nastupima tokom prethodnih 15 godina (2009-2023/4), kao i računarski izračunate karakteristike pesme od strane Spotify platforme. U ovom skupu podataka se takođe nalaze podaci o individualnom glasanju žirija i publike u prethodnih par godina, i ovi podaci o glasanju će biti kompletirani dodavanjem podataka iz [pomoćnog skupa podataka](https://www.kaggle.com/datasets/datagraver/eurovision-song-contest-scores-19752019) koji će dati podatke iz prvih godina u izabranom vremenskom periodu.

**Metodologija**

Kvalitet nastupa će biti definisan preko konačnih rezultata takmičenja, i glasanje države će biti smatrano da vrednuje kvalitet nastupa ukoliko uspeva da isprati generalno mišljenje svetske publike. Trend ukusa glasaša će biti vrednovan putem podataka o nastupu, te će ovaj motiv glasanja biti prisutan ukoliko bodovi često idu nastupima sa sličnim karakteristikama. Politički motivi će biti primetni u glasanju države ukoliko se raspored glasova ne slaže sa ostala dva faktora, na korist ili štetu određene države.

Tokom 15 takmičenja izabrani žiri država nije bio sastavljen od istih osoba, pa ukus ove strane glasanja može biti promenljiv zbog različitog sastava glasača, međutim, ovo neće biti moguće uzeti u obzir zbog nedostatka kompletnih podataka o sastavima žirija i glasanja individualnih članova. Takođe, očekivano je da se tokom vremena promeni generalni ukus i trend muzičkih nastupa na takmičenju, kao i da promenljivost političke slike putem promene generalnog kulturnog stava naroda i individualnih događaja koji mogu da promene internacionalni odnos država. Generalni trendovi takmičenja se mogu uračunati u algoritme tako što će se normalizovati podaci prema godini takmičenja ukoliko je potrebno, dok se individualni motivi političke scene moraju, kao i slučaju žirija, identifikovati analizom konačnih rezultata projekta.

Planirano je korišćenje varijacionog enkodera, gde će biti izvršena analiza podataka skrivenog sloja za potrebe prepoznavanja koja sklonost je prisutna kod kojih država. Podaci će takođe po potrebi biti popunjeni dodatnim generisanim podacima zbog relativno male količine podataka i kako bi se prezentovali ekstremi moguće sklonosti glasanja

**Metod evaluacije**

Pri treniranju autoenkodera kvalitet će biti meren korišćenjem _KL divergence_ funkcije. Nakon završetka treninga planirana je ručna analiza podataka kako bi se potencijalno primetilo da li su već primećene sklonosti u glasanju primetne i u rezultujućim podacima, što bi pokazalo da model ima mogućnost detekcije i do tada neprimećenih sklonosti glasanja.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
