### ISSUE TITLE
Detekcija phishing e-mail poruka

### ISSUE THREAD

**Issue by branislavroljic** [ftn-ai-lab/nm-2023#12]
### Tim
Branislav Roljić R2 6/2023

### Definicija problema

Projekat se spaja sa projektom iz SIAP-a. 
**Detekcija _phishing e-mail_ poruka.**
Svake godine, _phishing_ rezultuje gubicima u vrijednosti milijardi dolara i predstavlja značajnu prijetnju za internet ekonomiju. Od izbijanja koronavirusa 2019. godine (COVID-19), pitanje phishing napada postalo je predmet velikog interesovanja. Među svim metodama, zlonamjerni korisnici često preferiraju napade putem e-mail poruka, jer su takvi napadi teži za detekciju.

### Skup podataka
Kao skup podataka koristiće se kombinacija [Nazario i SpamAssassin ](https://zenodo.org/records/8339691). U slučaju potrebe za većim skupom podataka, vršiće se kombinovanje ovih skupova sa ostalim skupovima sa linka. 
Takođe, kako maliciozni URL-ovi igraju veliku ulogu u detekciji, dodatno će se koristiti i [skup  podataka](https://www.kaggle.com/datasets/harisudhan411/phishing-and-legitimate-urls) sa maliciozim URL-ovima.

### Metodologija
Kako se projekat spaja sa projektom iz SIAP-a, vršiće se poređenje rezultata tamo obrađenih modela sa LSTM, finetuned BERT i CNN pristupima, te će se osim tijela email poruka posmatrati i druge značajne karakteristike(zaglavlje, informacije o pošiljaocu, URL-ovi...). Takođe, [rad](https://www.mdpi.com/2079-9292/12/1/232) predlaže upotrebu LSTM-CNN arhitekture, kombinujući 1D konvolucioni sloj i LSTM sloj u cilju postizanja boljih rezultata, pa će i navedena arhitektura biti uključena.

### Evaluacija
Kao metrike za evaluaciju će biti korištene: _Recall, Precision, Accuracy, F1-score, AUC-ROC, False Positive Rate (FPR)_ i _False Negative Rate (FNR)_

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by branislavroljic** [comment]
[Repozitorijum](https://github.com/branislavroljic/phishing-detector)
