### ISSUE TITLE
Detekcija i klasifikacija ugroženih vrsta životinja

### ISSUE THREAD

**Issue by SaraJokic** [ftn-ai-lab/nm-2023#14]
### **Detekcija i klasifikacija ugroženih vrsta životinja**
https://github.com/SaraJokic/Neuronske-mreze

### Tim
Tamara Krgović RA 112/2023
Sara Jokić RA 109/2023

### Definicija problema
Očuvanje biodiverziteta u savremenom svetu predstavlja kompleksan problem sa sve većim značajem. Naš projekat ima za cilj razvoj sistema za detekciju i klasifikaciju ugroženih vrsta životinja, kroz primenu dubokih neuronskih mreža. Sistem će koristiti 4 poznate arhitekture konvolutivnih neuronskih mreža za analizu vizuelnih karakteristika životinja u svom staništu i klasifikovati ih u 3 klase (panda, polarni medved, beloglavi orao). Na kraju, napravićemo uporedni pregled performansi korišćenih modela.

### Skup podataka
Budući da radimo detekciju i klasifikaciju ugroženih vrsta životinja, odlučile smo da ćemo samostalno prikupiti skup podataka uzimanjem fotografija sa njihovih staništa. Koristićemo live prenos sa kamera postavljenih u zoo vrtu i u prirodnim staništima životinja kako bismo obezbedile dovoljno obimne i raznolike podatke. Skup podataka će sadržati slike zabeležene tokom 24 časa, obuhvatajući različite periode dana i omogućavajući analizu ponašanja životinja u različitim svetlosnim uslovima. S obzirom na to da se životinje kreću, izbacićemo slike sa praznim kadrovima i obratiti posebnu pažnju na situacije gde je vidljivost lošija.
Koristićemo sledeće live prenose: 
https://www.youtube.com/@ExploreLiveNatureCams/streams
https://www.youtube.com/@iPandaChannel/streams 
https://www.youtube.com/@SanDiegoZoo/streams 
https://www.youtube.com/@explorebears/streams
https://www.youtube.com/@FOBBVCAM 
https://www.youtube.com/@FriendsoftheReddingEagles/streams 

### Metodologija
Live kamere korišćene za sakupljanje slika u dataset-u su kamere visoke rezolucije, ipak plan je odraditi predprocesiranje slika, takodje razmatraćemo i primenu augmentacije slika ukoliko se pokaže da je neophodno izbalansirati broj slika između klasa. Detekciju objekata na slikama ćemo implementirati sami, a detektovane objekte ćemo sačuvati kao nove slike sa kojima ćemo trenirati modele.
Za ekstrakciju osobina koristićemo sledeće poznate arhitekture konvolutivnih neuronskih mreža:  ResNet, VGGNet, GoogleNet, AlexNet, nad kojima ćemo izvršiti fine tuning prema potrebama našeg skupa podataka, a klasifikator ćemo sami trenirati. Cilj je postići što veću tačnost modela i što bolju klasifikaciju na jednu od 3 klase.

### Evaluacija
Skup podataka će biti podeljen u odnosu 80% za trening i 20% za testiranje, čime omogućavamo modelu da nauči važne karakteristike, dok se testiranje vrši na nepoznatim podacima. Evaluaciju modela ćemo koristiti tačnost, preciznost, odziv i F1 rezultat.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
