### ISSUE TITLE
Klasifikacija EEG signala na osnovu sentimenta emocija ispitanika

### ISSUE THREAD

**Issue by YoNoSoyMarinero** [ftn-ai-lab/nm-2023#6]
### **Tim**

Link ka repozitorijumu: https://github.com/YoNoSoyMarinero/EGG-Sentiment-Classification/tree/main

Miloš Marinković E2 35/2023
Vladan Đorđević E2 87/2023
### **Definicija problema**
Klasifikacija sirovih EEG signala na osnovu sentimenta video snimka koji ispitanik posmatra. Klasifikacija se vrši u pet klasa: gađenje, strah, tuga, neutralno stanje i sreća. Cilj je pronaći korisna obeležja za obučavanje modela mašinskog i dubokog učeanja kako bi se dobila što veća tačnost klasifikacije. 
### **Skup podataka**
Za treniranje modela korišćena je SEED-V baza podataka. SEED-V baza podataka predstavlja izuzetno vredan resurs za istraživače u oblasti analize emotivnih stanja putem elektroencefalografa (EEG). Ova baza obuhvata pet različitih emocionalnih klasa: sreća, tuga, gađenje, strah i neutralnost. Svi podaci u bazi generisani su korišćenjem sirovih EEG signala dobijenih snimanjem 62-kanalnog NCI NeuroScan sistema, pri uzorkovanju od 1 kHz.  Baza sadrži EEG signale 16 učesnika i svakom učesniku prikazivani su kratki snimci u tri serije po 15 snimaka, pri čemu svaki snimak sadrži tematiku jedne od pomenutih emocija. Za bazu je potrebna licenca koja se može dobiti na sledećem linku: 
 https://bcmi.sjtu.edu.cn/home/seed/downloads.html#seed-v-access-anchor
### **Metodologija**
Ideja je da se projektni zadatak spoji sa predmetom "Sistemi za istraživanje i analizu podataka", na kom će biti isprobani neki modeli mašinskog učenja i na kraju porediti performanse sa dubokim učenjem. Što se tiče tipa neuronskih mreža koje bismo koristili predlažeom dva tipa: 
1. DNN čiju bismo arhitekturu sami pokušali da projektujemo i koja bi se obučavala na vremensko-frekvencijskim obeležjima izvučenim iz sirovih signala. 
2. CNN koja bi se obučavala na spektrogramima signala. Ideja je koristiti pretreniran model koji radi klasifikaciju spektrograma audio signala poput Guglovog VGGish.
### **Evaluacija**
Kako su podaci u njoj neujednačeni, zbog različitog trajanja prikazivanih video snimaka, u skladu sa predlozima samih kreatora SEED baze podataka koristiće se makro F1 mera da bi se evaluirala mera tačnosti klasifikatora.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
