### ISSUE TITLE
Detekcija i klasifikacija vozila na Terazijama 

### ISSUE THREAD

**Issue by MarijaGolubovic** [ftn-ai-lab/nm-2023#7]
**Tim**
Link do repozitorijuma: https://github.com/MarijaGolubovic/vahicle_recognition

Marija Golubović E2 11/2023
Mehaela Osmajić E2 13/2023

**Definicija problema**
Saobraćajne gužve predstavljaju ozbiljan problem savremenog društva. Jedan od ključnih atributa koji utiče na gužvu i koje se često analizira prilikom traženja uskih grla na saobraćajnicama je struktura saobraćaja. Upotrebnom modela mašinskog učenja za detekciju i klasifikaciju objekata postiže se brza i efikasna analiza strukture saobraćaja.

**Skup podataka**
Pošto radimo detekciju i klasifikaciju saobraćaja na Terazijama, odlučile smo da ćemo same sakupiti skup podataka.  Pošto za analizu koristimo live prenos sa kamere, nije nam problem sakupiti dovoljno velik skup podataka. Skup podataka bi činile fotografije nastala u različito doba dana, u različitim vremenskim uslovima i u situacijam kada ima puno saobraćaja i kada ga nema uopšte. Poseban izazov će biti detekcija u uslovima loše vidljivosti. 
Za anotaciju podataka ćemo koristiti _[Roboflow](https://roboflow.com/)_ alat za anotiranje. Pošto projekat spajamo sa projektom iz predmeta Sistemi za istraživanje i analizu podataka (SIAP), gdje radimo predikciju saobraćajnih gužvi, radićemo klasifikaciju saobraćaja u tri klase:
- automobile
- autobuse i 
- kamione.

Link do live kamere na Terazijama: https://www.youtube.com/@BeogradCom/streams

**Metodologija**
Kao što sam ranije napomenula projekat spajamo sa predmetom SIAP za koji su nam potrebni valjani podaci. Pošto nam je potrebna detekcija i klasifikacija objekata odlučile smo se za dva modela:
- _YOLOV8_ i
- _SSD_ (_Single Shot Multibox Detector_)

Ove modele ćemo dotrenirati sa našim podacima i uporedićemo njihove performanse. Kako bi pratili kretanje vozila u više frejmova, koristićemo _object tracking_.  Na ovaj način želimo pratiti koliko vremena vozilu treba da pređe od jedne do druge tačke na frejmu, kako bi na osnovu tih informacija izračunale relativnu brzinu.
I ovaj put ćemo koristiti dva pristupa:
- Object Tracking  od _Ultralitics_-a koji se često koristi u kombinaciji sa _YOLO_ modelom i
- _Bytetrack_ kao alternativu _Ultralitics_-ovom riješenju.

**Metod evaluacije**
Pošto očekujemo nebalansirane klasa i važno nam je da znamo koliko imamo _False Negatives_ i _False Positives_  detekcija, odlučile smo da ćemo kao mjeru performansi koristiti _F score_.

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
