### ISSUE TITLE
Predikcija saobraćajnih gužvi Srbije

### ISSUE THREAD

**Issue by pavleglusac** [ftn-ai-lab/nm-2023#8]
## Tim
Nevena Radešić R2 2/2023
Pavle Glušac R2 15/2023

## Definicija problema
Potrebno je prikupiti i obraditi snimke saobraćaja sa nadzornih kamera na teritoriji Republike Srbije i analizirati da li postoje trendovi koji se pojavljuju u zavisnosti od vremena dana, kao i od vremenske prognoze. Potrebno je i modelovati protok vozila saobraćaja i omogućiti predikciju broja vozila. Analizom trendova moglo bi se ustanoviti u kojim vremenskim periodima je saobraćaj više opterećen, što bi imalo primene i za fizička lica kao i za kompanije.

## Skup podataka
Podatke ćemo sami sakupiti koristeći dostupne izvore poput [AMSS sajta](https://kamere.amss.org.rs/) (za granični prelaz Horgoš, iz oba smera kretanja), i [“Uživo kamere”](https://uzivokamere.com/) sajta (za Takovsku ulicu u Beogradu). Plan je da dobavljamo sirove slike skidajući ih na svakih 5 minuta, nakon čega nad njima vršimo brojanje vozila upotrebom pretreniranog YOLOv5 modela. Istovremeno bismo skupljali podatke o vremenskim uslovima, koristeći OpenWeather API. Rezultujući skup podataka bi sadržao atribute: datum i vreme, broj vozila, temperatura, vremenski uslovi (sunčano, oblačno, kišovito, snežno). Estimacija za broj podataka prikupljenih tokom mesec dana je 25920 slika (864 dnevno) za sva tri izvora (8640 po izvoru mesečno). Rezolucija videa iz Horgoša je 640 x 360 px, dok je za Beograd 704x576 px.

## Metodologija
Kako smo problem predstavili kao analizu vremenske serije, opredelili smo se za sledeće arhitekture
- GRU
- LSTM

Modele ćemo trenirati od nule. Cilj nam je predikcija broja vozila u datom trenutku. Izvršićemo trening datih modela i poredićemo njihove performanse.

## Evaluacija
Za evaluaciju predikcije broja vozila koristiće se RMSE, gde ćemo računati odstupanje predviđenog broja vozila i tačnog broja vozila. Razmeru veličine trening i test skupa ćemo odrediti nakon što sakupimo podatke, dok sada estimiramo da ćemo imati podelu 90:10.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by pavleglusac** [comment]
https://github.com/pavleglusac/SIAP-NM
